name: Release to NuGet

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Mono
      run: |
        sudo apt update
        sudo apt install -y mono-complete

    - name: Setup NuGet CLI
      run: |
        curl -sSL https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
        chmod +x ./nuget.exe

    - name: Pack nugets
      run: mono nuget.exe pack DrawingCaptcha.nuspec

    - name: Push to NuGet
      run: mono nuget.exe push "*.nupkg" -ApiKey ${{secrets.nuget_api_key}} -Source https://api.nuget.org/v3/index.json
