name: Release to NuGet

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' 

    - name: Pack nugets
      run: dotnet pack DrawingCaptcha.nuspec --output .

    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
